name: Java CI with Localtunnel (Bypass Tunnel Reminder)

on:
  workflow_dispatch:  # Manuelles Auslösen

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      # 1. Repository auschecken
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. JDK 21 einrichten
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      # 3. gradlew ausführbar machen
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 4. Gradle-Abhängigkeiten cachen
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 5. JPro-Server im Hintergrund starten
      - name: Start JPro server
        run: |
          nohup ./gradlew jprorun > jpro.log 2>&1 &
          echo "Warte 10 Sekunden auf den Start des JPro-Servers..."
          sleep 10

      # 6. Node.js einrichten (zum Installieren von localtunnel)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 7. localtunnel installieren
      - name: Install localtunnel
        run: npm install -g localtunnel

      # 8. localtunnel starten, öffentliche URL ermitteln und den Reminder-Page-Bypass testen
      - name: Start localtunnel and get public URL
        id: localtunnel
        run: |
          echo "Starte localtunnel auf Port 8080..."
          # Starte localtunnel im Hintergrund; lt schreibt Logs in lt.log
          lt --port 8080 > lt.log 2>&1 &
          echo "Warte 10 Sekunden, bis localtunnel initialisiert ist..."
          sleep 10
          # Extrahiere die öffentliche URL aus lt.log
          LT_URL=$(grep -o 'https://[a-z0-9\-]*\.loca.lt' lt.log | head -n 1)
          if [ -z "$LT_URL" ]; then
            echo "Fehler: Keine öffentliche URL von localtunnel erhalten."
            exit 1
          fi
          echo "Gefundene URL: $LT_URL"
          # Teste, ob der Tunnel-Benachrichtigungsbildschirm (Reminder) erscheint, indem ein Request mit zusätzlichen Headern gesendet wird:
          TEST_CONTENT=$(curl --silent -H "bypass-tunnel-reminder: true" -H "User-Agent: CustomAgent/1.0" "$LT_URL")
          if echo "$TEST_CONTENT" | grep -qi "Tunnel Password:"; then
            echo "Fehler: Der Tunnel Reminder erscheint – Bypass funktioniert nicht."
            exit 1
          fi
          echo "Bypass erfolgreich. Dein JPro-Server ist öffentlich erreichbar unter: $LT_URL"
          echo "::set-output name=public_url::$LT_URL"

      # 9. Workflow offen halten, damit der Tunnel für Tests verfügbar bleibt
      - name: Wait for manual testing
        run: |
          echo "Server läuft – 5 Minuten Zeit zum Testen."
          sleep 300
