name: Java CI with Localtunnel (Continuous Log Output)

on:
  workflow_dispatch:  # Manuelles Auslösen

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      # 1. Code auschecken
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. JDK 21 einrichten
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      # 3. gradlew ausführbar machen
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 4. Gradle-Abhängigkeiten cachen
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 5. Öffentliche IP abrufen und anzeigen (Tunnel-Passwort)
      - name: Display Public IP (Tunnel Password)
        run: |
          PUBLIC_IP=$(curl --silent ifconfig.me)
          echo "Tunnel-Passwort (Public IP): $PUBLIC_IP"

      # 6. JPro-Server im Hintergrund starten
      - name: Start JPro server
        run: |
          nohup ./gradlew jprorun > jpro.log 2>&1 &
          echo "Warte 10 Sekunden auf den Start des JPro-Servers..."
          sleep 10

      # 7. Node.js einrichten (für localtunnel)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 8. localtunnel installieren
      - name: Install localtunnel
        run: npm install -g localtunnel

      # 9. localtunnel starten und öffentliche URL ermitteln
      - name: Start localtunnel and get public URL
        id: lt
        run: |
          echo "Starte localtunnel auf Port 8080..."
          lt --port 8080 > lt.log 2>&1 &
          echo "Warte 10 Sekunden, bis localtunnel initialisiert ist..."
          sleep 10
          LT_URL=$(grep -o 'https://[a-z0-9\-]*\.loca.lt' lt.log | head -n 1)
          if [ -z "$LT_URL" ]; then
            echo "Fehler: Keine öffentliche URL von localtunnel erhalten."
            exit 1
          fi
          echo "Dein JPro-Server ist öffentlich erreichbar unter: $LT_URL"
          echo "::set-output name=public_url::$LT_URL"

      # 10. jpro.log kontinuierlich in der Konsole anzeigen für 5 Minuten
      - name: Stream jpro.log to console
        run: |
          echo "Streaming jpro.log für die nächsten 5 Minuten..."
          timeout 300 tail -f jpro.log
